"""Regenerate the skeleton of DATA_DICTIONARY.md from the files themselves.

The definition column is completed by hand; this script rebuilds everything else, so the
dictionary can be refreshed when an artifact changes. It never overwrites hand-written
definitions silently: it writes DATA_DICTIONARY.generated.md beside the existing file and
leaves the merge to a person.

Run:  python replication/make_dictionary.py      (or: make dictionary)
"""
from __future__ import annotations

import csv
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def describe_csv(path: pathlib.Path) -> list[str]:
    try:
        with path.open(newline="", encoding="utf-8") as fh:
            reader = csv.reader(fh)
            header = next(reader, [])
            first = next(reader, [])
    except (UnicodeDecodeError, StopIteration):
        return []
    rows = []
    for i, col in enumerate(header):
        sample = first[i] if i < len(first) else ""
        kind = "number" if re.fullmatch(r"-?\d+(\.\d+)?([eE]-?\d+)?", sample or "x") \
            else "text"
        rows.append(f"| `{col}` | {kind} | example `{sample[:24]}` | |")
    return rows


def main() -> int:
    lines = ["# Data dictionary (generated skeleton)", "",
             "Regenerated by `replication/make_dictionary.py`. Merge hand-written",
             "definitions from DATA_DICTIONARY.md into this file before replacing it.", ""]
    for base in ["data/release", "data/processed"]:
        for path in sorted((ROOT / base).rglob("*")):
            if not path.is_file():
                continue
            lines += [f"## `{path.relative_to(ROOT).as_posix()}`", ""]
            if path.suffix == ".json":
                try:
                    obj = json.loads(path.read_text(encoding="utf-8"))
                except json.JSONDecodeError:
                    obj = {}
                status = obj.get("status", "") if isinstance(obj, dict) else ""
                if status:
                    lines += [f"Status as recorded in the file: {status}", ""]
                keys = list(obj)[:24] if isinstance(obj, dict) else []
                lines.append("Top-level keys: " + ", ".join(f"`{k}`" for k in keys))
            elif path.suffix == ".csv":
                rows = describe_csv(path)
                if rows:
                    lines += ["| column | type | example | definition |", "|---|---|---|---|"]
                    lines += rows
                else:
                    lines.append("(empty or non-tabular)")
            else:
                lines.append("(documentation file)")
            lines.append("")
    out = ROOT / "DATA_DICTIONARY.generated.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
