"""Generate the allocation paper's measured-value macros.

PLAYBOOK SECTION 3. Every number in that paper's prose enters through a \\result{}
macro defined here, so each traces to the artifact that produced it. The \\result
command itself is defined in the shared paper/results_macros.tex, which this file is
read alongside; this file only adds entries.

Run:  python framework/stress_scoping/gen_macros_alloc.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "results_macros_alloc.tex"


def main():
    D = json.loads((HERE / "dispersion_decomposition.json").read_text())
    R = json.loads((HERE / "reallocation_result.json").read_text())
    one = D["by_outcome"]["y_hh_1"]

    M = {}
    # the decomposition
    M["AllocNObs"] = f'{one["n_obs"]:,}'
    M["AllocNBanksHist"] = f'{one["n_banks"]:,}'
    M["AllocMixRSq"] = f'{100*one["mix_r2"]:.1f}'
    M["AllocPersistent"] = f'{100*one["persistent_bank_specific"]:.1f}'
    M["AllocTransitory"] = f'{100*one["transitory"]:.1f}'
    M["AllocMixOfForecastable"] = f'{100*one["mix_share_of_forecastable"]:.1f}'
    M["AllocAutocorr"] = f'{one["resid_autocorr"]:.3f}'
    M["AllocMixThree"] = f'{100*D["by_outcome"]["y_hh_3"]["mix_share_of_forecastable"]:.1f}'
    M["AllocMixTotal"] = f'{100*D["by_outcome"]["y_tot_1"]["mix_share_of_forecastable"]:.1f}'
    M["AllocMixPre"] = f'{100*D["by_period"]["pre_crisis_2001_2006"]["mix_r2"]:.1f}'
    M["AllocMixCrisis"] = f'{100*D["by_period"]["crisis_2007_2010"]["mix_r2"]:.1f}'
    M["AllocMixPost"] = f'{100*D["by_period"]["post_2011_2021"]["mix_r2"]:.1f}'

    # the reallocation
    M["AllocBanks"] = f'{R["banks"]:,}'
    M["AllocBanksHistory"] = f'{R["banks_with_history"]:,}'
    M["AllocAssetCoverage"] = f'{100*R["coverage_of_assets"]:.1f}'
    M["AllocSystemLoss"] = f'{R["system_loss_bn"]:,.0f}'
    M["AllocBreachPro"] = str(R["breaching_prorata"])
    M["AllocBreachSpec"] = str(R["breaching_specific"])
    M["AllocBreachBoth"] = str(R["breaching_both"])
    M["AllocOnlyPro"] = str(R["only_prorata"])
    M["AllocOnlySpec"] = str(R["only_specific"])
    M["AllocJaccard"] = f'{R["jaccard_overlap_of_breach_sets"]:.3f}'
    M["AllocSpearman"] = f'{R["spearman_of_loss_ordering"]:.3f}'
    M["AllocRho"] = f'{R["shrinkage_rho"]:.3f}'
    for c, v in R["factor_spread"].items():
        tag = "".join(w.capitalize() for w in c.split("_"))
        M["AllocF" + tag + "Low"] = f'{v["p10"]:.2f}'
        M["AllocF" + tag + "Med"] = f'{v["median"]:.2f}'
        M["AllocF" + tag + "High"] = f'{v["p90"]:.2f}'

    nf = R["newly_flagged"]
    M["AllocNewN"] = str(nf["n"])
    M["AllocNewMedianAssets"] = f'{nf["median_assets_bn"]:.2f}'
    M["AllocNewTotalAssets"] = f'{nf["total_assets_bn"]:,.0f}'
    M["AllocNewPctAssets"] = f'{nf["pct_system_assets"]:.1f}'
    M["AllocNewCommunity"] = str(nf["by_size_class"].get("community (under 1bn)", 0))
    M["AllocNewMidsize"] = str(nf["by_size_class"].get("midsize (1 to 10bn)", 0))
    M["AllocNewRegional"] = str(nf["by_size_class"].get("regional (10 to 100bn)", 0))
    M["AllocNewLevPro"] = f'{nf["median_leverage_under_prorata"]:.4f}'
    M["AllocNewLevSpec"] = f'{nf["median_leverage_under_specific"]:.4f}'

    B = json.loads((HERE / "robustness.json").read_text())
    jac = [r["jaccard"] for r in B["by_severity"]]
    M["AllocJacSevLow"] = f'{min(jac):.3f}'
    M["AllocJacSevHigh"] = f'{max(jac):.3f}'
    rj = [r["jaccard"] for r in B["by_rho"]]
    M["AllocJacRhoLow"] = f'{min(rj):.3f}'
    M["AllocJacRhoHigh"] = f'{max(rj):.3f}'
    for r in B["by_severity"]:
        tag = str(r["severity_multiplier"]).replace(".", "p")
        M["AllocSevPro" + tag] = str(r["breach_prorata"])
        M["AllocSevSpec" + tag] = str(r["breach_specific"])
        M["AllocSevJac" + tag] = f'{r["jaccard"]:.3f}'
        M["AllocSevLoss" + tag] = f'{r["system_loss_bn"]:,.0f}'

    lines = ["% AUTO-GENERATED by framework/stress_scoping/gen_macros_alloc.py.",
             "% Read alongside paper/results_macros.tex, which defines \\result."]
    for k, v in M.items():
        lines.append(f"\\expandafter\\def\\csname result@{k}\\endcsname{{{v}}}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} with {len(M)} macros")
    for k, v in M.items():
        print(f"  {k:26s} {v}")


if __name__ == "__main__":
    main()
