"""Generate data/SOURCES.md from the fetch manifests. Never hand-edited."""
import json, pathlib, datetime

ROOT = pathlib.Path(__file__).parents[1]
RAW = ROOT / "data" / "raw"

HEAD = """# SOURCES

Generated by `src/gen_sources.py` from the fetch manifests. Do not edit by hand.
Every figure in any table or note traces to a row here.

Generated: {ts}

"""

STATIC = [
    dict(name="O*NET Database 31.0 (text)", file="data/raw/onet/db_31_0_text.zip",
         url="https://www.onetcenter.org/dl_files/database/db_31_0_text.zip",
         ident="O*NET 31.0, released August 2026",
         retrieved="2026-09-19",
         licence="O*NET is provided by the US Department of Labor under CC BY 4.0. "
                 "Attribution required.",
         notes="Used for the Physical AI Exposure Index. Tables used: Abilities, "
               "Work Activities, Work Context, Scales Reference, Occupation Data."),
    dict(name="ACS PUMS 2023 1-year, person records",
         file="data/raw/pums/csv_pus.zip",
         url="https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/csv_pus.zip",
         ident="psam_pusa.csv, psam_pusb.csv; 3,405,809 person records",
         retrieved="2026-09-19",
         licence="US Census Bureau public use microdata, public domain.",
         notes="Variables used: SERIALNO, OCCP, PWGTP, WAGP, ADJINC, AGEP, WKHP."),
    dict(name="ACS PUMS 2023 1-year, housing records",
         file="data/raw/pums/csv_hus.zip",
         url="https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/csv_hus.zip",
         ident="psam_husa.csv, psam_husb.csv; 1,620,290 household records",
         retrieved="2026-09-19",
         licence="US Census Bureau public use microdata, public domain.",
         notes="Variables used: SERIALNO, WGTP, TEN, MRGP, VALP, HINCP, NP."),
    dict(name="2018 Census Occupation Code List and Crosswalk",
         file="data/raw/crosswalk/census2018_occ_soc.xlsx",
         url="https://www2.census.gov/programs-surveys/demo/guidance/industry-occupation/"
             "2018-occupation-code-list-and-crosswalk.xlsx",
         ident="Sheet '2018 Census Occ Code List'; 530 usable OCCP-to-SOC rows",
         retrieved="2026-09-19",
         licence="US Census Bureau, public domain.",
         notes="Maps PUMS OCCP codes to 2018 SOC, to join PAEI to PUMS."),
]


def main():
    out = [HEAD.format(ts=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))]

    out.append("## FRED series (Federal Reserve Z.1, BEA NIPA, BIS via FRED)\n")
    man = json.loads((RAW / "fred" / "_manifest.json").read_text())
    out.append("| Series ID | Title | Units | Freq | Source | Last updated | Retrieved | Leg |")
    out.append("|---|---|---|---|---|---|---|---|")
    for sid, m in man.items():
        out.append(f"| `{sid}` | {m['title']} | {m['units']} | {m['freq']} | "
                   f"{m['source']} | {m['last_updated']} | {m['retrieved']} | {m['leg']} |")
    out.append("")
    out.append("All FRED series retrieved as CSV from "
               "`https://fred.stlouisfed.org/graph/fredgraph.csv?id=<SERIES_ID>`. "
               "Titles, units, frequency and source above are read from the FRED series "
               "page at fetch time, not asserted by the pipeline (see decision D1). "
               "FRED terms of use: data are redistributed from the cited original sources; "
               "the original source governs.\n")

    out.append("## Bulk datasets\n")
    for s in STATIC:
        out.append(f"### {s['name']}\n")
        out.append(f"- Local file: `{s['file']}`")
        out.append(f"- URL: {s['url']}")
        out.append(f"- Identifier: {s['ident']}")
        out.append(f"- Retrieved: {s['retrieved']}")
        out.append(f"- Licence: {s['licence']}")
        out.append(f"- Notes: {s['notes']}\n")

    sec = RAW / "sec" / "_manifest.json"
    out.append("## SEC EDGAR (Leg A, Tier 2)\n")
    if sec.exists():
        m = json.loads(sec.read_text())
        ok = sum(1 for v in m.values() if v["ok"])
        out.append(f"Retrieved {ok} of {len(m)} company-concept series.\n")
    else:
        out.append("NOT RETRIEVED. SEC returns HTTP 403 to this environment "
                   "(\"Your Request Originates from an Undeclared Automated Tool\"). "
                   "SEC fair-access policy requires a declared contact address in the "
                   "User-Agent header. Blocked pending owner decision, see "
                   "`notes/open_questions.md` Q1 and decision D8.\n")

    out.append("## Blocked or paywalled, not used\n")
    out.append("| Source | Status | Needed for |")
    out.append("|---|---|---|")
    out.append("| SEC EDGAR XBRL | HTTP 403, undeclared automated tool | Leg A Tier 2 |")
    out.append("| BLS OES employment and wages | HTTP 403 to this environment | "
               "employment weights for PAEI |")
    out.append("| Census API (PUMS) | requires free API key | "
               "not needed, bulk files used instead |")
    out.append("| IFR World Robotics | paid | robot stock and shipments |")
    out.append("| Scopus / Web of Science | subscription | WS0 systematic coverage |")
    out.append("| Preqin | paid | private credit to AI infrastructure |")
    out.append("")

    (ROOT / "data" / "SOURCES.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote data/SOURCES.md ({len(man)} FRED series, {len(STATIC)} bulk datasets)")


if __name__ == "__main__":
    main()
