"""Generate data/SOURCES.md from the fetch manifests. Never hand-edited."""
import json, pathlib, datetime

ROOT = pathlib.Path(__file__).parents[1]
RAW = ROOT / "data" / "raw"

HEAD = """# SOURCES

Generated by `src/gen_sources.py` from the fetch manifests. Do not edit by hand.
Every figure in any table or note traces to a row here.

Generated: {ts}

"""

STATIC = [
    dict(name="2026 OASDI and Medicare Trustees Reports, summary tables",
         file="data/raw/owner/SSA_2026_Trustees_Summary_Tables.md",
         url="https://www.ssa.gov/oact/trsum/",
         ident="all 13 summary tables, extracted text",
         retrieved="2026-09-20",
         licence="US government work, public domain.",
         notes="PLACED BY THE OWNER. NO SAVED ORIGINAL EXISTS: the source is an HTML page, "
               "not a PDF. Verified instead by arithmetic reconciliation of every accounting "
               "identity the tables contain, 23 checks and 0 failures, in "
               "src/owner_files.py. Used for OASDI payroll income 1,322.6bn and HI payroll "
               "income 403.2bn (Table 5), reserves at end 2025 (Table 4), depletion dates "
               "(Tables 7, 8, 10 and 12). SUPERSEDES the derived HI figure of 286.2bn and "
               "the use of 462.4bn, which is HI TOTAL income, as a payroll denominator."),
    dict(name="CBO, Preliminary Estimate of the Effects of H.R. 748, the CARES Act",
         file="data/raw/owner/CBO_hr748_ORIGINAL.pdf",
         url="https://www.cbo.gov/system/files/2020-04/hr748.pdf",
         ident="revised 27 April 2020, 35 pages, publication 56334",
         retrieved="2026-09-20",
         licence="US government work, public domain.",
         notes="PLACED BY THE OWNER with its extracted text at "
               "data/raw/owner/CBO_HR748_CARES_2020-04-27_Extracted.txt. The extraction is "
               "VERIFIED AGAINST THIS ORIGINAL in src/owner_files.py: page count, every "
               "headline figure present in both, and 37 of 40 sampled sentences verbatim in "
               "the PDF text layer. Used for the CITED public budget reference point, a "
               "408bn revenue decrease inside a 1.7tn deficit increase over 2020 to 2030, "
               "replacing a threshold derived from FRED."),
    dict(name="NY Fed Household Debt and Credit, 2026Q2, data workbook",
         file="data/raw/manual/NYFed_HHDC_2026Q2_data.xlsx",
         url="https://www.newyorkfed.org/medialibrary/interactives/householdcredit/"
             "data/xls/HHD_C_Report_2026Q2.xlsx",
         ident="the report's own chart data workbook",
         retrieved="2026-09-20",
         licence="Federal Reserve Bank of New York, public.",
         notes="Used for the AUTO LOAN BALANCE of 1,713bn at 2026Q2 ('Page 3 Data'), which "
               "REPLACES FRED MVLOAS, discontinued after 2024Q4 and two years stale against "
               "every other input; and for the auto 90+ delinquency rate of 5.49 percent "
               "('Page 12 Data'), a trigger dashboard row previously recorded as not "
               "retrieved. The PDF gives auto only as a quarterly percentage change, which "
               "is why the workbook is used."),
    dict(name="O*NET Database 31.0 (text)", file="data/raw/onet/db_31_0_text.zip",
         url="https://www.onetcenter.org/dl_files/database/db_31_0_text.zip",
         ident="O*NET 31.0, released August 2026",
         retrieved="2026-09-19",
         licence="O*NET is provided by the US Department of Labor under CC BY 4.0. "
                 "Attribution required.",
         notes="Used for the Physical AI Exposure Index. Tables used: Abilities, "
               "Work Activities, Work Context, Scales Reference, Occupation Data."),
    dict(name="ACS PUMS 2023 1-year, person records",
         file="data/raw/pums/csv_pus.zip",
         url="https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/csv_pus.zip",
         ident="psam_pusa.csv, psam_pusb.csv; 3,405,809 person records",
         retrieved="2026-09-19",
         licence="US Census Bureau public use microdata, public domain.",
         notes="Variables used: SERIALNO, OCCP, PWGTP, WAGP, ADJINC, AGEP, WKHP."),
    dict(name="ACS PUMS 2023 1-year, housing records",
         file="data/raw/pums/csv_hus.zip",
         url="https://www2.census.gov/programs-surveys/acs/data/pums/2023/1-Year/csv_hus.zip",
         ident="psam_husa.csv, psam_husb.csv; 1,620,290 household records",
         retrieved="2026-09-19",
         licence="US Census Bureau public use microdata, public domain.",
         notes="Variables used: SERIALNO, WGTP, TEN, MRGP, VALP, HINCP, NP."),
    dict(name="2018 Census Occupation Code List and Crosswalk",
         file="data/raw/crosswalk/census2018_occ_soc.xlsx",
         url="https://www2.census.gov/programs-surveys/demo/guidance/industry-occupation/"
             "2018-occupation-code-list-and-crosswalk.xlsx",
         ident="Sheet '2018 Census Occ Code List'; 530 usable OCCP-to-SOC rows",
         retrieved="2026-09-19",
         licence="US Census Bureau, public domain.",
         notes="Maps PUMS OCCP codes to 2018 SOC, to join PAEI to PUMS."),
]


def main():
    out = [HEAD.format(ts=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"))]

    out.append("## FRED series (Federal Reserve Z.1, BEA NIPA, BIS via FRED)\n")
    man = json.loads((RAW / "fred" / "_manifest.json").read_text())
    out.append("| Series ID | Title | Units | Freq | Source | Last updated | Retrieved | Leg |")
    out.append("|---|---|---|---|---|---|---|---|")
    for sid, m in man.items():
        out.append(f"| `{sid}` | {m['title']} | {m['units']} | {m['freq']} | "
                   f"{m['source']} | {m['last_updated']} | {m['retrieved']} | {m['leg']} |")
    out.append("")
    out.append("All FRED series retrieved as CSV from "
               "`https://fred.stlouisfed.org/graph/fredgraph.csv?id=<SERIES_ID>`. "
               "Titles, units, frequency and source above are read from the FRED series "
               "page at fetch time, not asserted by the pipeline (see decision D1). "
               "FRED terms of use: data are redistributed from the cited original sources; "
               "the original source governs.\n")

    out.append("## Bulk datasets\n")
    for s in STATIC:
        out.append(f"### {s['name']}\n")
        out.append(f"- Local file: `{s['file']}`")
        out.append(f"- URL: {s['url']}")
        out.append(f"- Identifier: {s['ident']}")
        out.append(f"- Retrieved: {s['retrieved']}")
        out.append(f"- Licence: {s['licence']}")
        out.append(f"- Notes: {s['notes']}\n")

    sec = RAW / "sec" / "_manifest.json"
    out.append("## SEC EDGAR (Leg A, Tier 2)\n")
    if sec.exists():
        m = json.loads(sec.read_text())
        ok = sum(1 for v in m.values() if v["ok"])
        out.append(f"Retrieved {ok} of {len(m)} company-concept series.\n")
    else:
        out.append("NOT RETRIEVED. SEC returns HTTP 403 to this environment "
                   "(\"Your Request Originates from an Undeclared Automated Tool\"). "
                   "SEC fair-access policy requires a declared contact address in the "
                   "User-Agent header. Blocked pending owner decision, see "
                   "`notes/open_questions.md` Q1 and decision D8.\n")

    out.append("## Blocked or paywalled, not used\n")
    out.append("| Source | Status | Needed for |")
    out.append("|---|---|---|")
    out.append("| SEC EDGAR XBRL | HTTP 403, undeclared automated tool | Leg A Tier 2 |")
    out.append("| BLS OES employment and wages | HTTP 403 to this environment | "
               "employment weights for PAEI |")
    out.append("| Census API (PUMS) | requires free API key | "
               "not needed, bulk files used instead |")
    out.append("| IFR World Robotics | paid | robot stock and shipments |")
    out.append("| Scopus / Web of Science | subscription | WS0 systematic coverage |")
    out.append("| Preqin | paid | private credit to AI infrastructure |")
    out.append("")

    (ROOT / "data" / "SOURCES.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote data/SOURCES.md ({len(man)} FRED series, {len(STATIC)} bulk datasets)")


if __name__ == "__main__":
    main()
